{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sparkapplication.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "sparkapplication.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  entryPoints:
    {{- range .Values.ingress.entryPoints }}
    - {{ . }}
    {{- end}}
  routes:
    {{- range .Values.ingress.routes }}
    - match: {{ .match }}
      kind: Rule
      services:
        {{- range .services}}
        - name: {{ .name }}
          port: {{ .port }}
          kind: Service
        {{- end}}
    {{- end }}
  {{- end }}
