---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: openeo
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "vito-docker.artifactory.vgt.vito.be/openeo"
  imagePullPolicy: Always
  mainApplicationFile: local:///usr/local/lib/python3.7/dist-packages/openeogeotrellis/deploy/probav-mep.py
  arguments:
    - '--env=dev'
  sparkConf:
    "spark.executorEnv.DRIVER_IMPLEMENTATION_PACKAGE": "openeogeotrellis"
    "spark.extraListeners": "org.openeo.sparklisteners.CancelRunawayJobListener"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.5
      name: openeo-driver
    serviceAccount: sparkoperator-1593094592-spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.5
  deps:
    files:
      - 'local:///opt/log4j.properties'
      - 'local:///opt/layercatalog.json'
    pyFiles:
      - 'local:///opt/custom_processes.py'
      - 'local:///opt/cropsar-1.3.2.20200618.176+develop-py3-none-any.whl'
    jars:
      - 'local:///opt/geotrellis-extensions-1.3.0-SNAPSHOT.jar'
      - 'local:///opt/geotrellis-backend-assembly-0.4.5-openeo.jar'
