---
driver:
  cores: 2
  memory: "4096m"
executor:
  cores: 2
  instances: 1
  memory: "4096m"
imagePullPolicy: "IfNotPresent"
ingress:
  enabled: false
jmxPort: 8090
pythonVersion: 3
service:
  enabled: false
  type: "ClusterIP"
sparkVersion: "2.4.5"
serviceAccount:
  create: false
